name: smart_games_solver
description: "Multi-game platform with Rubik solver, 2048, Sudoku, and Caro games."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # User
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  http: ^1.2.0

  # Rubik
  cuber: ^0.4.0
  camera: ^0.10.5+9
  image: ^4.1.7
  exif: ^3.1.2
  
  # Rubik 3D
  vector_math: ^2.1.4
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/caro/
