name: sang3_e4_nhom7
description: Mini-game Nhom 7
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    # User
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  http: ^1.2.0

    # Rubik
  cuber: ^0.4.0 # Thuat toan Kociemba (two-phase)
  camera: ^0.10.5+9 # Mau
  image: ^4.1.7 # Image processing
  exif: ^3.1.2 # EXIF metadata reading
  
    # Rubik 3D
  vector_math: ^2.1.4
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/g2048_background.jpg
    - assets/images/g2048_icon.jpg
    - assets/images/icon.jpg
    - assets/images/caro_icon.jpg
    - assets/images/sudoku_icon.jpg
    - assets/rubik_faces/
    - assets/caro/
